### PR TITLE
Adds implementation for MessageBox component

### PR DESCRIPTION
**Pull request by BenjaminEckardt**
Due to lacking specs only implemented for `SeverityLevel.INFO`

### CODE REVIEW

**Comment by BenjaminEckardt** [comment]
image

**Review by efekaptan — APPROVED** [review]
All is fine, just a small question. Is line-height matches the designs? It looked smaller(narrower) to me.

**Review by x057 — APPROVED** [review]
Looks good to me 👍

**Comment by BenjaminEckardt** [comment]
Thanks for reviewing. Will check the line-height.

**Review by manojkrishna1991 — APPROVED** [review]

**Comment by BenjaminEckardt** [comment]
Checked line height, none have been specified. Therefore, we'll go with the default behaviour. When some implicit expectations have not been met, we'll handle them afterwards.

**Pull request merged**
